language: python
python:
  - "3.6"
services:
  - postgresql

env:
  global:
    - APP_SETTINGS ='testing'

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

before_script:
  - "psql -c 'create database storemanagerdb;' -U postgres"
  - "psql -c 'create database test_store_managerdb;' -U postgres"
  
script:
  - python3 -m pytest -v --cov api/

after_success:
  - coveralls
